apiVersion: v1
kind: Pod
metadata:
   name: todoapp-pod
   namespace: todoapp
spec:
  containers:
    - name: todoapp
    image: dianahorban/todoapp:3.0.0
    ports:
    - containerPort: 8000
    livenessProbe:
      httpGet:
        path: /health
        port: 8000
      initialDelaySeconds: 10
      periodSeconds: 5
    readinessProbe:
      httpGet:
        path: /ready
        port: 8000
      initialDelaySeconds: 10
      periodSeconds: 5
